source 'https://github.com/CocoaPods/Specs.git'
pod 'TwilioConversationsClient', :podspec => 'https://media.twiliocdn.com/sdk/ios/conversations/latest/TwilioConversationsClient.podspec'
pod 'TwilioCommon', :podspec => 'https://media.twiliocdn.com/sdk/ios/common/latest/TwilioCommon.podspec'
